<?php

/**
* @file
*/

/**
* Implementation of hook_init().
*/
function html_tree_init() {

    if(user_access('Html Tree Export')){
        $path = drupal_get_path('module', 'html_tree');
        drupal_add_js($path .'/html_tree.js');
        drupal_add_css($path .'/html_tree.css');
    }

}

/**
* Implementation of hook_menu().
*/
function html_tree_menu() {

    $items['html_tree/export'] = array(
        'page callback' => 'html_tree_export',
        'access callback' => 'user_access',
        'access arguments' => array('Html Tree Export'),
        'type' => MENU_CALLBACK,
        );

    $items['html_tree/load'] = array(
        'page callback' => 'html_tree_load',
        'access callback' => 'user_access',
        'access arguments' => array('Html Tree Export'),
        'type' => MENU_CALLBACK,
        );

    return $items;
}

/**
* Implementation of hook_theme().
*/
function html_tree_theme() {
    $items = array(
        'html_tree' => array(
            'arguments' => array('content' => NULL),
            'template' => 'html-tree',
            ),
        );
    return $items;
}


/**
* Implementation of hook_theme().
*/
function html_tree_perm() {
    return array('Html Tree Export');
}

function html_tree_export(){
    $status = true;
    if($_POST['data']){
        $filename = time().'_html_tree.html.txt';
        $temp_path =file_directory_path() . '/';
        $file = $temp_path . $filename;
        $file_uri = file_create_url($file);
        $create_file = file_put_contents($file, $_POST['data'], FILE_APPEND);
        if ( $create_file === FALSE ) {
            $output = 'There was a problem creating the html file.';
            $status = FALSE;
        }else{
            $output = 'The file was successfuly created';
        }
    }
    drupal_json(array('status' => $status, 'output' => $output, 'redirect' => $file_uri));


}
function html_tree_load(){
    $output = theme('html_tree');
    return drupal_json(array('status' => TRUE, 'output' => $output));
}
